language: node_js
cache:
  directories:
    - "$HOME/.npm"
    - "node_modules"
install:
  - npm ci
  - npm run reinitialize
jobs:
  include:
    - stage: "Build"                # naming the Tests stage
      script: npm run build
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: npm run test
    - name: "Linting"
      script: npm run lint
