name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm run reinitialize

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Coverage
      run: npm run coverage
