name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: NVM use
      uses: dcodeIO/setup-node-nvm@master

    - name: Install dependencies
      run: npm run reinitialize

    - name: Build
      run: npm run build

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Coverage
      run: npm run coverage
